vim.api.nvim_set_hl(0, "red", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "green", { fg = "#9ece6a" })
vim.api.nvim_set_hl(0, "yellow", { fg = "#FFFF00" })
vim.api.nvim_set_hl(0, "orange", { fg = "#f09000" })

vim.fn.sign_define("DapBreakpoint", { text = "⬤", texthl = "red", linehl = "", numhl = "" })
vim.fn.sign_define( "DapBreakpointCondition", { text = "", texthl = "red", linehl = "", numhl = "" })
vim.fn.sign_define( "DapBreakpointRejected", { text = "⬤", texthl = "orange", linehl = "", numhl = "" })
vim.fn.sign_define("DapStopped", { text = "", texthl = "green", linehl = "", numhl = "" })
vim.fn.sign_define( "DapLogPoint", { text = "⬤", texthl = "yellow", linehl = "", numhl = "" })
