return {
  -- {
  --   "folke/noice.nvim",
  --   event = "VeryLazy",
  --   opts = {
  --     -- add any options here
  --   },
  --   config = function()
  --     require("noice").setup {
  --       lsp = {
  --         -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
  --         override = {
  --           ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
  --           ["vim.lsp.util.stylize_markdown"] = true,
  --           ["cmp.entry.get_documentation"] = true, -- requires hrsh7th/nvim-cmp
  --         },
  --         signature = { enabled = false },
  --         message = {
  --           enabled = false,
  --         },
  --         progress = {
  --           enabled = false,
  --           view = "mini",
  --         },
  --       },
  --       routes = {
  --         {
  --           view = "notify",
  --           filter = { event = "msg_showmode" },
  --         },
  --       },
  --       views = {
  --         cmdline_popup = {
  --           border = {
  --             style = "single",
  --             padding = { 0, 1 },
  --           },
  --           position = {
  --             row = 15,
  --             col = "50%",
  --           },
  --           size = {
  --             width = 60,
  --             height = "auto",
  --           },
  --         },
  --         popupmenu = {
  --           relative = "editor",
  --           position = {
  --             row = 18,
  --             col = "50%",
  --           },
  --           size = {
  --             width = 60,
  --             height = 10,
  --           },
  --           border = {
  --             style = "single",
  --             padding = { 0, 1 },
  --           },
  --           win_options = {
  --             winhighlight = { Normal = "Normal", FloatBorder = "DiagnosticInfo" },
  --           },
  --         },
  --       },
  --       notify = {
  --         enabled = false,
  --         view = "notify",
  --       },
  --       messages = {
  --         enabled = true,
  --         view = "mini",
  --       },
  --       popupmenu = {
  --         enabled = true,
  --         -- bakend = "nui",
  --         position = {
  --           row = "auto",
  --           col = "auto",
  --         },
  --         size = {
  --           width = 120,
  --           height = "auto",
  --         },
  --         border = {
  --           --@type _.NuiBorderStyle
  --           style = "double",
  --           --@type _.NuiBorderPadding
  --           padding = { 0, 1 },
  --         },
  --         win_options = {
  --           winhighlight = {
  --             Normal = "NoicePopupmenu", -- Normal | NoicePopupmenu
  --             FloatBorder = "NoicePopupmenuBorder", -- DiagnosticInfo | NoicePopupmenuBorder
  --             CursorLine = "NoicePopupmenuSelected",
  --             PmenuMatch = "NoicePopupmenuMatch",
  --           },
  --         },
  --       },
  --
  --       -- you can enable a preset for easier configuration
  --       presets = {
  --         bottom_search = true, -- use a classic bottom cmdline for search
  --         -- command_palette = true, -- position the cmdline and popupmenu together
  --         long_message_to_split = true, -- long messages will be sent to a split
  --         inc_rename = false, -- enables an input dialog for inc-rename.nvim
  --         lsp_doc_border = false, -- add a border to hover docs and signature help
  --       },
  --     }
  --   end,
  --   dependencies = {
  --     "MunifTanjim/nui.nvim",
  --     "rcarriga/nvim-notify",
  --   },
  -- },
}
